### ISSUE TITLE
URL in Emacs help and feature suggestions

### ISSUE THREAD

**Issue by technician77** [dotemacs/ipcalc.el#8]
First, shouldn't it be github.com instead of org?
![image](https://user-images.githubusercontent.com/18722291/29245090-49b1a6b8-7fce-11e7-8bc9-c4de04be7c56.png)

Feature Suggestions:
- Support for standard mask input and (showing the corresponding prefix notation)
- Support subnet planing. I mean something like this
   Input: 192.168.0.0/24
   Output1: (Standard as currently)
   Output2: Showing potential networks in base mask /24
    /25 (Prefix)      255.255.255.128 (Standard Mask)      2 (Number of Networks)    126 (Number of hosts)
     ...
    /30   255.255.255.252 64 2
If possible output should be as an org mode tree and output 2 is the headline.
When unfolding a tree it should show the potential network details. For /30 in the upper example that would be:
1  (Index-Number) 192.168.0.0(Network Address) 192.168.0.1-192.168.0.2 (Host Range)
2 192.168.0.4 192.168.0.5-192.168.0.3
...
Alternatively the subnet planing might be called using a different command.

**Comment by dotemacs** [comment]
Hi @technician77 

Thanks for the feedback.

Regarding the URL, you're absolutely right!
Do you want to do a PR for it?

And regarding the subnet planning, do you mind creating an example output and posting it in a nicely formatted fashion as a reply? Just so that I can see what you mean exactly?

Thanks

**Comment by technician77** [comment]
No, just fix it please.

Well, something like that, it's a quick sketch done by hand.

(Org mode)
```
Base-Network 192.168.0.0/24

Potential-Networks:
Prefix       Subnet      Networks    Hosts
* /24    255.255.255.0    001        254
* /25    255.255.255.0    002        126
* /26    255.255.255.0    004        062
* /27    255.255.255.0    008        030
 Network-Number    Network-Address            Hostrange 
     0001          192.168.0.000     192.168.0.001-192.168.0.030
     0002          192.168.0.032     192.168.0.033-192.168.0.062
     0003          192.168.0.064     192.168.0.065-192.168.0.094
     0004          192.168.0.096     192.168.0.097-192.168.0.126
     0005          192.168.0.128     192.168.0.129-192.168.0.158
     0006          192.168.0.160     192.168.0.161-192.168.0.190
     0007          192.168.0.192     192.168.0.193-192.168.0.222
     0008          192.168.0.224     192.168.0.225-192.168.0.254
* /28    255.255.255.0    016        014
* /29    255.255.255.0    032        006
* /30    255.255.255.0    064        002
* /31    255.255.255.0    128        002
```

**Comment by dotemacs** [comment]
Hello @technician77 

sorry for the delay in dealing with this issue.

I've corrected the link to GitHub:
https://github.com/dotemacs/ipcalc.el/commit/cb29b7f5f54721143dcce7175443ec572b8c5619

As for the other feature, I wont be really using it as per your suggestion, so I'd rather not add something to the project that I'll then have to maintain.

Thanks for your time :)
